export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL';
export const COMMENT_CREATE_RESET = 'COMMENT_CREATE_RESET';

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL';
export const COMMENT_LIST_RESET = 'COMMENT_LIST_RESET';

export const COMMENT_EDIT_REQUEST = 'COMMENT_EDIT_REQUEST';
export const COMMENT_EDIT_SUCCESS = 'COMMENT_EDIT_SUCCESS';
export const COMMENT_EDIT_FAIL = 'COMMENT_EDIT_FAIL';
export const COMMENT_EDIT_RESET = 'COMMENT_EDIT_RESET';

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL';
export const COMMENT_DELETE_RESET = 'COMMENT_DELETE_RESET';

export const COMMENT_VOTE_REQUEST = 'COMMENT_VOTE_REQUEST';
export const COMMENT_VOTE_SUCCESS = 'COMMENT_VOTE_SUCCESS';
export const COMMENT_VOTE_FAIL = 'COMMENT_VOTE_FAIL';


export const IMAGE_COMMENT_CREATE_REQUEST = 'IMAGE_COMMENT_CREATE_REQUEST';
export const IMAGE_COMMENT_CREATE_SUCCESS = 'IMAGE_COMMENT_CREATE_SUCCESS';
export const IMAGE_COMMENT_CREATE_FAIL = 'IMAGE_COMMENT_CREATE_FAIL';
export const IMAGE_COMMENT_CREATE_RESET = 'IMAGE_COMMENT_CREATE_RESET';

export const IMAGE_COMMENT_LIST_REQUEST = 'IMAGE_COMMENT_LIST_REQUEST';
export const IMAGE_COMMENT_LIST_SUCCESS = 'IMAGE_COMMENT_LIST_SUCCESS';
export const IMAGE_COMMENT_LIST_FAIL = 'IMAGE_COMMENT_LIST_FAIL';
export const IMAGE_COMMENT_LIST_RESET = 'IMAGE_COMMENT_LIST_RESET';

export const IMAGE_COMMENT_EDIT_REQUEST = 'IMAGE_COMMENT_EDIT_REQUEST';
export const IMAGE_COMMENT_EDIT_SUCCESS = 'IMAGE_COMMENT_EDIT_SUCCESS';
export const IMAGE_COMMENT_EDIT_FAIL = 'IMAGE_COMMENT_EDIT_FAIL';
export const IMAGE_COMMENT_EDIT_RESET = 'IMAGE_COMMENT_EDIT_RESET';

export const IMAGE_COMMENT_DELETE_REQUEST = 'IMAGE_COMMENT_DELETE_REQUEST';
export const IMAGE_COMMENT_DELETE_SUCCESS = 'IMAGE_COMMENT_DELETE_SUCCESS';
export const IMAGE_COMMENT_DELETE_FAIL = 'IMAGE_COMMENT_DELETE_FAIL';
export const IMAGE_COMMENT_DELETE_RESET = 'IMAGE_COMMENT_DELETE_RESET';

export const IMAGE_COMMENT_VOTE_REQUEST = 'IMAGE_COMMENT_VOTE_REQUEST';
export const IMAGE_COMMENT_VOTE_SUCCESS = 'IMAGE_COMMENT_VOTE_SUCCESS';
export const IMAGE_COMMENT_VOTE_FAIL = 'IMAGE_COMMENT_VOTE_FAIL';
