export const FRIEND_REQUEST_CREATE_REQUEST = 'FRIEND_REQUEST_CREATE_REQUEST';
export const FRIEND_REQUEST_CREATE_SUCCESS = 'FRIEND_REQUEST_CREATE_SUCCESS';
export const FRIEND_REQUEST_CREATE_FAIL = 'FRIEND_REQUEST_CREATE_FAIL';

export const FRIENDS_LIST_REQUEST = 'FRIENDS_LIST_REQUEST';
export const FRIENDS_LIST_SUCCESS = 'FRIENDS_LIST_SUCCESS';
export const FRIENDS_LIST_FAIL = 'FRIENDS_LIST_FAIL';
export const FRIENDS_LIST_RESET = 'FRIENDS_LIST_RESET';

export const FRIENDS_SUGGESTIONS_LIST_REQUEST = 'FRIENDS_SUGGESTIONS_LIST_REQUEST';
export const FRIENDS_SUGGESTIONS_LIST_SUCCESS = 'FRIENDS_SUGGESTIONS_LIST_SUCCESS';
export const FRIENDS_SUGGESTIONS_LIST_FAIL = 'FRIENDS_SUGGESTIONS_LIST_FAIL';
export const FRIENDS_SUGGESTIONS_LIST_RESET = 'FRIENDS_SUGGESTIONS_LIST_RESET';

export const FRIENDS_REQUESTS_LIST_REQUEST = 'FRIENDS_REQUESTS_LIST_REQUEST';
export const FRIENDS_REQUESTS_LIST_SUCCESS = 'FRIENDS_REQUESTS_LIST_SUCCESS';
export const FRIENDS_REQUESTS_LIST_FAIL = 'FRIENDS_REQUESTS_LIST_FAIL';
export const FRIENDS_REQUESTS_LIST_RESET = 'FRIENDS_REQUESTS_LIST_RESET';

export const FRIENDS_REQUESTS_SENT_REQUEST = 'FRIENDS_REQUESTS_SENT_REQUEST';
export const FRIENDS_REQUESTS_SENT_SUCCESS = 'FRIENDS_REQUESTS_SENT_SUCCESS';
export const FRIENDS_REQUESTS_SENT_FAIL = 'FRIENDS_REQUESTS_SENT_FAIL';
export const FRIENDS_REQUESTS_SENT_RESET = 'FRIENDS_REQUESTS_SENT_RESET';

export const FRIENDS_REQUESTS_RECEIVED_REQUEST = 'FRIENDS_REQUESTS_RECEIVED_REQUEST';
export const FRIENDS_REQUESTS_RECEIVED_SUCCESS = 'FRIENDS_REQUESTS_RECEIVED_SUCCESS';
export const FRIENDS_REQUESTS_RECEIVED_FAIL = 'FRIENDS_REQUESTS_RECEIVED_FAIL';
export const FRIENDS_REQUESTS_RECEIVED_RESET = 'FRIENDS_REQUESTS_RECEIVED_RESET';

export const FRIEND_REQUEST_STATUS_UPDATE_REQUEST = 'FRIEND_REQUEST_STATUS_UPDATE_REQUEST';
export const FRIEND_REQUEST_STATUS_UPDATE_SUCCESS = 'FRIEND_REQUEST_STATUS_UPDATE_SUCCESS';
export const FRIEND_REQUEST_STATUS_UPDATE_FAIL = 'FRIEND_REQUEST_STATUS_UPDATE_FAIL';
export const FRIEND_REQUEST_STATUS_UPDATE_RESET = 'FRIEND_REQUEST_STATUS_UPDATE_RESET';

export const FRIEND_UNFRIEND_REQUEST = 'FRIEND_UNFRIEND_REQUEST';
export const FRIEND_UNFRIEND_SUCCESS = 'FRIEND_UNFRIEND_SUCCESS';
export const FRIEND_UNFRIEND_FAIL = 'FRIEND_UNFRIEND_FAIL';
