export const POST_MY_LIST_REQUEST = 'POST_MY_LIST_REQUEST';
export const POST_MY_LIST_SUCCESS = 'POST_MY_LIST_SUCCESS';
export const POST_MY_LIST_FAIL = 'POST_MY_LIST_FAIL';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_RESTORE_REQUEST = 'POST_RESTORE_REQUEST';
export const POST_RESTORE_SUCCESS = 'POST_RESTORE_SUCCESS';
export const POST_RESTORE_FAIL = 'POST_RESTORE_FAIL';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET';

export const POST_IMAGE_UPLOAD_REQUEST = 'POST_IMAGE_UPLOAD_REQUEST';
export const POST_IMAGE_UPLOAD_SUCCESS = 'POST_IMAGE_UPLOAD_SUCCESS';
export const POST_IMAGE_UPLOAD_FAIL = 'POST_IMAGE_UPLOAD_FAIL';

export const POST_IMAGES_LIST_REQUEST = 'POST_IMAGES_LIST_REQUEST';
export const POST_IMAGES_LIST_SUCCESS = 'POST_IMAGES_LIST_SUCCESS';
export const POST_IMAGES_LIST_FAIL = 'POST_IMAGES_LIST_FAIL';

export const POST_IMAGE_DELETE_REQUEST = 'POST_IMAGE_DELETE_REQUEST';
export const POST_IMAGE_DELETE_SUCCESS = 'POST_IMAGE_DELETE_SUCCESS';
export const POST_IMAGE_DELETE_FAIL = 'POST_IMAGE_DELETE_FAIL';

export const POST_IMAGE_SET_MAIN_REQUEST = 'POST_IMAGE_SET_MAIN_REQUEST';
export const POST_IMAGE_SET_MAIN_SUCCESS = 'POST_IMAGE_SET_MAIN_SUCCESS';
export const POST_IMAGE_SET_MAIN_FAIL = 'POST_IMAGE_SET_MAIN_FAIL';