export const SAVED_POST_CREATE_REQUEST = 'SAVED_POST_CREATE_REQUEST';
export const SAVED_POST_CREATE_SUCCESS = 'SAVED_POST_CREATE_SUCCESS';
export const SAVED_POST_CREATE_FAIL = 'SAVED_POST_CREATE_FAIL';

export const SAVED_POST_DETAILS_REQUEST = 'SAVED_POST_DETAILS_REQUEST';
export const SAVED_POST_DETAILS_SUCCESS = 'SAVED_POST_DETAILS_SUCCESS';
export const SAVED_POST_DETAILS_FAIL = 'SAVED_POST_DETAILS_FAIL';
export const SAVED_POST_DETAILS_RESET = 'SAVED_POST_DETAILS_RESET';

export const SAVED_POST_UPDATE_REQUEST = 'SAVED_POST_UPDATE_REQUEST';
export const SAVED_POST_UPDATE_SUCCESS = 'SAVED_POST_UPDATE_SUCCESS';
export const SAVED_POST_UPDATE_FAIL = 'SAVED_POST_UPDATE_FAIL';
export const SAVED_POST_UPDATE_RESET = 'SAVED_POST_UPDATE_RESET';

export const SAVED_POSTS_LIST_REQUEST = 'SAVED_POSTS_LIST_REQUEST';
export const SAVED_POSTS_LIST_SUCCESS = 'SAVED_POSTS_LIST_SUCCESS';
export const SAVED_POSTS_LIST_FAIL = 'SAVED_POSTS_LIST_FAIL';
export const SAVED_POSTS_LIST_RESET = 'SAVED_POSTS_LIST_RESET';

export const SAVED_POST_DELETE_REQUEST = 'SAVED_POST_DELETE_REQUEST';
export const SAVED_POST_DELETE_SUCCESS = 'SAVED_POST_DELETE_SUCCESS';
export const SAVED_POST_DELETE_FAIL = 'SAVED_POST_DELETE_FAIL';

export const COLLECTION_CREATE_REQUEST = 'COLLECTION_CREATE_REQUEST';
export const COLLECTION_CREATE_SUCCESS = 'COLLECTION_CREATE_SUCCESS';
export const COLLECTION_CREATE_FAIL = 'COLLECTION_CREATE_FAIL';

export const COLLECTION_DETAILS_REQUEST = 'COLLECTION_DETAILS_REQUEST';
export const COLLECTION_DETAILS_SUCCESS = 'COLLECTION_DETAILS_SUCCESS';
export const COLLECTION_DETAILS_FAIL = 'COLLECTION_DETAILS_FAIL';
export const COLLECTION_DETAILS_RESET = 'COLLECTION_DETAILS_RESET';

export const COLLECTION_UPDATE_REQUEST = 'COLLECTION_UPDATE_REQUEST';
export const COLLECTION_UPDATE_SUCCESS = 'COLLECTION_UPDATE_SUCCESS';
export const COLLECTION_UPDATE_FAIL = 'COLLECTION_UPDATE_FAIL';
export const COLLECTION_UPDATE_RESET = 'COLLECTION_UPDATE_RESET';

export const COLLECTIONS_LIST_REQUEST = 'COLLECTIONS_LIST_REQUEST';
export const COLLECTIONS_LIST_SUCCESS = 'COLLECTIONS_LIST_SUCCESS';
export const COLLECTIONS_LIST_FAIL = 'COLLECTIONS_LIST_FAIL';
export const COLLECTIONS_LIST_RESET = 'COLLECTIONS_LIST_RESET';

export const COLLECTION_DELETE_REQUEST = 'COLLECTION_DELETE_REQUEST';
export const COLLECTION_DELETE_SUCCESS = 'COLLECTION_DELETE_SUCCESS';
export const COLLECTION_DELETE_FAIL = 'COLLECTION_DELETE_FAIL';
