export const STORY_MY_LIST_REQUEST = 'STORY_MY_LIST_REQUEST';
export const STORY_MY_LIST_SUCCESS = 'STORY_MY_LIST_SUCCESS';
export const STORY_MY_LIST_FAIL = 'STORY_MY_LIST_FAIL';

export const STORY_DETAILS_REQUEST = 'STORY_DETAILS_REQUEST';
export const STORY_DETAILS_SUCCESS = 'STORY_DETAILS_SUCCESS';
export const STORY_DETAILS_FAIL = 'STORY_DETAILS_FAIL';

export const STORY_DELETE_REQUEST = 'STORY_DELETE_REQUEST';
export const STORY_DELETE_SUCCESS = 'STORY_DELETE_SUCCESS';
export const STORY_DELETE_FAIL = 'STORY_DELETE_FAIL';

export const STORY_RESTORE_REQUEST = 'STORY_RESTORE_REQUEST';
export const STORY_RESTORE_SUCCESS = 'STORY_RESTORE_SUCCESS';
export const STORY_RESTORE_FAIL = 'STORY_RESTORE_FAIL';

export const STORY_CREATE_REQUEST = 'STORY_CREATE_REQUEST';
export const STORY_CREATE_SUCCESS = 'STORY_CREATE_SUCCESS';
export const STORY_CREATE_FAIL = 'STORY_CREATE_FAIL';
export const STORY_CREATE_RESET = 'STORY_CREATE_RESET';

export const STORY_UPDATE_REQUEST = 'STORY_UPDATE_REQUEST';
export const STORY_UPDATE_SUCCESS = 'STORY_UPDATE_SUCCESS';
export const STORY_UPDATE_FAIL = 'STORY_UPDATE_FAIL';
export const STORY_UPDATE_RESET = 'STORY_UPDATE_RESET';

export const STORY_IMAGE_UPLOAD_REQUEST = 'STORY_IMAGE_UPLOAD_REQUEST';
export const STORY_IMAGE_UPLOAD_SUCCESS = 'STORY_IMAGE_UPLOAD_SUCCESS';
export const STORY_IMAGE_UPLOAD_FAIL = 'STORY_IMAGE_UPLOAD_FAIL';

export const STORY_IMAGES_LIST_REQUEST = 'STORY_IMAGES_LIST_REQUEST';
export const STORY_IMAGES_LIST_SUCCESS = 'STORY_IMAGES_LIST_SUCCESS';
export const STORY_IMAGES_LIST_FAIL = 'STORY_IMAGES_LIST_FAIL';

export const STORY_IMAGE_DELETE_REQUEST = 'STORY_IMAGE_DELETE_REQUEST';
export const STORY_IMAGE_DELETE_SUCCESS = 'STORY_IMAGE_DELETE_SUCCESS';
export const STORY_IMAGE_DELETE_FAIL = 'STORY_IMAGE_DELETE_FAIL';

export const STORY_IMAGE_SET_MAIN_REQUEST = 'STORY_IMAGE_SET_MAIN_REQUEST';
export const STORY_IMAGE_SET_MAIN_SUCCESS = 'STORY_IMAGE_SET_MAIN_SUCCESS';
export const STORY_IMAGE_SET_MAIN_FAIL = 'STORY_IMAGE_SET_MAIN_FAIL';