export const REACTIONS_POST_CREATE_REQUEST = 'REACTIONS_POST_CREATE_REQUEST';
export const REACTIONS_POST_CREATE_SUCCESS = 'REACTIONS_POST_CREATE_SUCCESS';
export const REACTIONS_POST_CREATE_FAIL = 'REACTIONS_POST_CREATE_FAIL';
export const REACTIONS_POST_CREATE_RESET = 'REACTIONS_POST_CREATE_RESET';

export const REACTIONS_POST_LIST_REQUEST = 'REACTIONS_POST_LIST_REQUEST';
export const REACTIONS_POST_LIST_SUCCESS = 'REACTIONS_POST_LIST_SUCCESS';
export const REACTIONS_POST_LIST_FAIL = 'REACTIONS_POST_LIST_FAIL';
export const REACTIONS_POST_LIST_RESET = 'REACTIONS_POST_LIST_RESET';

export const REACTIONS_POST_EDIT_REQUEST = 'REACTIONS_POST_EDIT_REQUEST';
export const REACTIONS_POST_EDIT_SUCCESS = 'REACTIONS_POST_EDIT_SUCCESS';
export const REACTIONS_POST_EDIT_FAIL = 'REACTIONS_POST_EDIT_FAIL';
export const REACTIONS_POST_EDIT_RESET = 'REACTIONS_POST_EDIT_RESET';

export const REACTIONS_POST_DELETE_REQUEST = 'REACTIONS_POST_DELETE_REQUEST';
export const REACTIONS_POST_DELETE_SUCCESS = 'REACTIONS_POST_DELETE_SUCCESS';
export const REACTIONS_POST_DELETE_FAIL = 'REACTIONS_POST_DELETE_FAIL';
export const REACTIONS_POST_DELETE_RESET = 'REACTIONS_POST_DELETE_RESET';

export const REACTIONS_COMMENT_CREATE_REQUEST = 'REACTIONS_COMMENT_CREATE_REQUEST';
export const REACTIONS_COMMENT_CREATE_SUCCESS = 'REACTIONS_COMMENT_CREATE_SUCCESS';
export const REACTIONS_COMMENT_CREATE_FAIL = 'REACTIONS_COMMENT_CREATE_FAIL';
export const REACTIONS_COMMENT_CREATE_RESET = 'REACTIONS_COMMENT_CREATE_RESET';

export const REACTIONS_COMMENT_LIST_REQUEST = 'REACTIONS_COMMENT_LIST_REQUEST';
export const REACTIONS_COMMENT_LIST_SUCCESS = 'REACTIONS_COMMENT_LIST_SUCCESS';
export const REACTIONS_COMMENT_LIST_FAIL = 'REACTIONS_COMMENT_LIST_FAIL';
export const REACTIONS_COMMENT_LIST_RESET = 'REACTIONS_COMMENT_LIST_RESET';

export const REACTIONS_COMMENT_EDIT_REQUEST = 'REACTIONS_COMMENT_EDIT_REQUEST';
export const REACTIONS_COMMENT_EDIT_SUCCESS = 'REACTIONS_COMMENT_EDIT_SUCCESS';
export const REACTIONS_COMMENT_EDIT_FAIL = 'REACTIONS_COMMENT_EDIT_FAIL';
export const REACTIONS_COMMENT_EDIT_RESET = 'REACTIONS_COMMENT_EDIT_RESET';

export const REACTIONS_COMMENT_DELETE_REQUEST = 'REACTIONS_COMMENT_DELETE_REQUEST';
export const REACTIONS_COMMENT_DELETE_SUCCESS = 'REACTIONS_COMMENT_DELETE_SUCCESS';
export const REACTIONS_COMMENT_DELETE_FAIL = 'REACTIONS_COMMENT_DELETE_FAIL';
export const REACTIONS_COMMENT_DELETE_RESET = 'REACTIONS_COMMENT_DELETE_RESET';
