export const WORKPLACE_CREATE_REQUEST = 'WORKPLACE_CREATE_REQUEST';
export const WORKPLACE_CREATE_SUCCESS = 'WORKPLACE_CREATE_SUCCESS';
export const WORKPLACE_CREATE_FAIL = 'WORKPLACE_CREATE_FAIL';

export const WORKPLACE_DETAILS_REQUEST = 'WORKPLACE_DETAILS_REQUEST';
export const WORKPLACE_DETAILS_SUCCESS = 'WORKPLACE_DETAILS_SUCCESS';
export const WORKPLACE_DETAILS_FAIL = 'WORKPLACE_DETAILS_FAIL';
export const WORKPLACE_DETAILS_RESET = 'WORKPLACE_DETAILS_RESET';

export const WORKPLACE_UPDATE_REQUEST = 'WORKPLACE_UPDATE_REQUEST';
export const WORKPLACE_UPDATE_SUCCESS = 'WORKPLACE_UPDATE_SUCCESS';
export const WORKPLACE_UPDATE_FAIL = 'WORKPLACE_UPDATE_FAIL';
export const WORKPLACE_UPDATE_RESET = 'WORKPLACE_UPDATE_RESET';

export const WORKPLACE_LIST_REQUEST = 'WORKPLACE_LIST_REQUEST';
export const WORKPLACE_LIST_SUCCESS = 'WORKPLACE_LIST_SUCCESS';
export const WORKPLACE_LIST_FAIL = 'WORKPLACE_LIST_FAIL';
export const WORKPLACE_LIST_RESET = 'WORKPLACE_LIST_RESET';

export const WORKPLACE_DELETE_REQUEST = 'WORKPLACE_DELETE_REQUEST';
export const WORKPLACE_DELETE_SUCCESS = 'WORKPLACE_DELETE_SUCCESS';
export const WORKPLACE_DELETE_FAIL = 'WORKPLACE_DELETE_FAIL';
