export default {
  THUMBS_UP: 1,
  THUMBS_DOWN: 2,
  // RED_HEART: 3,
  // SMILING_FACE: 4,
  // LAUGHING_FACE: 5,
  // WINKING_FACE: 6,
  // NEUTRAL_FACE: 7,
  // UNAMUSED_FACE: 8,
  // FEARFUL_FACE: 9,
  // CRYING_FACE: 10,
  // FROWNING_FACE: 11,
};
// export default {
//   THUMBS_UP: '👍',
//   THUMBS_DOWN: '👎',
//   RED_HEART: '❤️',
//   SMILING_FACE: '🙂',
//   LAUGHING_FACE: '😂',
//   WINKING_FACE: '😉',
//   NEUTRAL_FACE: '😐',
//   UNAMUSED_FACE: '😒',
//   FEARFUL_FACE: '😨',
//   CRYING_FACE: '😢',
//   FROWNING_FACE: '☹️',
// };