export default {
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  OPERATION_NOT_PERMITTED: 'OPERATION_NOT_PERMITTED',
  BAD_REQUEST: 'BAD_REQUEST',
  INVALID_LOGIN: 'INVALID_LOGIN'
};
